Repository seanathan-discordbot/Ayesha_Bot, pull requests merged in 2021-01, with the labels that each got.

#12 Cogs
  cogs/misc.py
  cogs/remind.py
Labels: Work in Progress, enhancement, help wanted

#14 Add ChangePrefix Capability
  seanathan.py
Labels: bug, enhancement, question

#18 Add Help Command
  cogs/HelpCommand.py
  seanathan.py
Labels: enhancement

#20 Update remind
  cogs/remind.py
Labels: Work in Progress, enhancement, good first issue

#41 Add a bug reporter command
  cogs/misc.py
Labels: enhancement
